/*
  Ek hoti hain exception , aur dushri chize hoti he exception handling .

  Exception me , exception aati he aur Exception handling, me ussi exception ko handle/report ki jaati he TRY Block ya CATCH Block ki madad/help se .
  
 Question - Difference betwwen exception and error ?
 Answer -     Exception - Exceptions are mostly due to program or causes by Programmerr. 
                        - Exceptions are Recoverable . means recover kr skate ho , handle ho skati hain , mange kr sakte ho .
                        - Exceptions are of Two Types -
                          a. Compile Time Exception (Checked Exception)
                          b. Runtime Exception (UnChecked Exception)

              Error - Errors are occured because of "lack of System Resoureces" ; not by our programs and thus, programmer cannot do anythings.
                    - Not Recoverable by programmerr . apako system adminisator waale person se deal karni hogi .
                    - Errors have only one Type - 
                          a. Runtime Exception (Unchecked Exception)  


  which is the parent class of all the classes in java ? 
  ans - Object class is the parent class of ........

  Throwable  is the parent class of Exception Class . 

To know, kon kiska parent class hain ; you have to first understand the hiraricary of exception . ; search in gooogle 





 */