/*
 
Abstraction  means hiding the Complexity / Data Hiding 

In Java Abstraction can be Achieved By 2 ways 
    1. By Abstract Class 
    2. By Interface

In Java To Create Class as Abstarct Class we Use " Abstract " Keyword .

IMP -  Abstract Class Have Minimum 1 Abstract Method . -- Old Version 

 Can be Abstracted only -- latest version of abstract meaning 

 In Abstract Class we Can Create Abstract Method as well as Concrete(Normal / Basic) Method . 

 When we Inherit the Abstract Class then it is Compulsory to Override Abstract Method Otherwise 
    You Have to make a child class . ALSO Abstrsct and the Child class also Inherit By Other Class 
      and Give Implementation of Abstract Method 


 No Instance / Object Can Be Created For Abstract Class .
 
 
 */