/*
 1. collection of Similar element same kind of array's element .

 2. it store same data Types (Homogenious)

 3. Contineous Memeory Allocation 

 4. Arrays Works on Index System and these Index Starts from zero (0) and end at (n-1) Index .

 5. Address of 1st Element of Arrays is called Base Address or Starting Address .
           int a[] = new int[5]

6. Types of Arrays - 
    a. One Dimentional Arrays 
    b. Two Dimentional Arrays 
    c. Multi-Dimentional Arrays 
    
7.     
 */