/*
 1. If you Apply Static keyword with any Method it is know as Static method

 2. Static Method is Belonging to Class rather than object of class .

 3. Static Method is called without need for creating Object Class 

 4. Static method Can Access Static Data memeber and can change value of it .

 5. Non-Static data Cannot be Accesed in Static method .

 6. Every Variable define / Decleare in Static Method is called Static Variable  . 
 
 7. if you call a Static method from other class then you Should use class name .

 8. we can also call Static method eith object of that class .
 */