/*
 WHEN VARIABLE ARE NOT KNOW THEN We will use the concept of var-args.

 Var-Args allowed the method to Accept Zero or Multiple Argument Before Var-Args , we use Overloding Methods

 * RULES OF VAR-ARGS -
  1. There can be only 1 Variable Argument in the Method . 
  2. Variable Argument Must be Last Argument of Function .
       ie  .. void sum (int ...a)
                 {
                                      - Syntax of var-args
                 }
 */